import type { Metadata } from "next";
import "./globals.css";
import s from "./layout/layout.module.scss";
import { GlobalContextProvider } from "./context/global.context";
import { SmoothScrollContextProvider } from "./layout/SmoothScroll";
import { LayoutOverlays } from "./layout/LayoutOverlays/LayoutOverlays";
import { cn } from "@/lib/utils";
import { prime_regular } from "@/fonts/fonts";
import {
  Header,
  Footer,
} from "./layout/index";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="fr"
    >
      <body 
        className={cn(
          "min-h-full flex flex-col",
          prime_regular.className,
        )}
      >
        <GlobalContextProvider>
          <SmoothScrollContextProvider>
            <div className={s.wrapper}>
              <Header />
              <main className="min-h-screen">
                {children}
              </main>
              <Footer />
            </div>
            <LayoutOverlays />
          </SmoothScrollContextProvider>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
